get-credential:
  tags: ["automation-team-aws"]
  script:
    - AWS_CREDENTIALS=$(cat ~/.aws/raw_credentials)
    - AWS_ACCESS_KEY_ID=$(echo $AWS_CREDENTIALS | jq '.AccessKeyId' --raw-output)
    - AWS_SECRET_ACCESS_KEY=$(echo $AWS_CREDENTIALS | jq '.SecretAccessKey' --raw-output)
    - AWS_SESSION_TOKEN=$(echo $AWS_CREDENTIALS | jq '.Token' --raw-output)
    - echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> credential.env
    - echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> credential.env
    - echo "AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN" >> credential.env
  artifacts:
    reports:
      dotenv: credential.env

use-case-1:
  stage: deploy
  script:
    - aws s3 ls
  dependencies:
    - get-credential
